const fs = require("fs");
const pool = require("../config/database");
const input = process.argv[2];
if (!input) throw new Error("Uso: node scripts/importarCatalogoRepuestosPorArea.js /tmp/consolidado_repuestos.json");
const data = JSON.parse(fs.readFileSync(input, "utf8"));
const normalize = (value) => String(value || "").trim().toLocaleUpperCase("es").normalize("NFD").replace(/[\u0300-\u036f]/g, "");
const validFamilies = new Set(["Mecanico", "Electrico", "Electronico", "Consumible"]);
(async () => { let conn; try {
  conn = await pool.getConnection(); await conn.beginTransaction();
  const areas = await conn.query("SELECT id, nombre FROM areas"); const areaByName = new Map(areas.map((area) => [normalize(area.nombre), area.id]));
  const masters = new Map(); const latestByCode = new Map();
  for (const row of data.catalogo) { const code = String(row.codigo || "").trim(); if (!code) continue; const current = masters.get(code); if (!current || Number(row.movimientos || 0) > Number(current.movimientos || 0)) masters.set(code, row); const date = String(row.ultima_solicitud || "").slice(0, 10); if (/^\d{4}-\d{2}-\d{2}$/.test(date) && date > String(latestByCode.get(code) || "")) latestByCode.set(code, date); }
  let created = 0; let updated = 0; let associations = 0; let areasMissing = 0;
  for (const row of masters.values()) { const code = String(row.codigo).trim(); const family = validFamilies.has(row.familia_tecnica) ? row.familia_tecnica : "Sin clasificar"; const latest = latestByCode.get(code) || null; const result = await conn.query(`INSERT INTO repuestos (codigo, descripcion, familia_tecnica, subfamilia_tecnica, estado_clasificacion, unidad_medida, criticidad, costo_ultimo, fecha_ultima_solicitud) VALUES (?, ?, ?, ?, ?, ?, 'Sin evaluar', ?, ?) ON DUPLICATE KEY UPDATE descripcion=VALUES(descripcion), familia_tecnica=VALUES(familia_tecnica), subfamilia_tecnica=VALUES(subfamilia_tecnica), estado_clasificacion=VALUES(estado_clasificacion), unidad_medida=VALUES(unidad_medida), costo_ultimo=VALUES(costo_ultimo), fecha_ultima_solicitud=CASE WHEN VALUES(fecha_ultima_solicitud) IS NULL THEN fecha_ultima_solicitud WHEN fecha_ultima_solicitud IS NULL OR VALUES(fecha_ultima_solicitud) > fecha_ultima_solicitud THEN VALUES(fecha_ultima_solicitud) ELSE fecha_ultima_solicitud END`, [code, String(row.descripcion || "Sin descripción").trim(), family, row.subfamilia_tecnica || null, row.estado_clasificacion === "Sugerida" ? "Sugerida" : "Pendiente", row.unidad || "unidad", Number(row.costo_ultimo || 0), latest]); if (result.affectedRows === 1) created += 1; else updated += 1; }
  const savedParts = await conn.query("SELECT id, codigo FROM repuestos"); const partByCode = new Map(savedParts.map((part) => [String(part.codigo).trim(), part.id]));
  for (const row of data.catalogo) { const idArea = areaByName.get(normalize(row.area)); const idPart = partByCode.get(String(row.codigo || "").trim()); if (!idArea || !idPart) { if (!idArea) areasMissing += 1; continue; } await conn.query(`INSERT INTO repuesto_areas (id_repuesto, id_area, movimientos_historicos, cantidad_consumida, costo_acumulado, ultima_solicitud, maquinas_origen, archivos_origen) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE movimientos_historicos=VALUES(movimientos_historicos), cantidad_consumida=VALUES(cantidad_consumida), costo_acumulado=VALUES(costo_acumulado), ultima_solicitud=VALUES(ultima_solicitud), maquinas_origen=VALUES(maquinas_origen), archivos_origen=VALUES(archivos_origen)`, [idPart, idArea, Number(row.movimientos || 0), Number(row.cantidad_consumida || 0), Number(row.costo_acumulado || 0), row.ultima_solicitud || null, row.maquinas_asociadas || null, row.archivos_origen || null]); associations += 1; }
  await conn.query("INSERT INTO importaciones (modulo, nombre_archivo, usuario_importador, registros_creados, registros_actualizados, registros_error, estado) VALUES ('Repuestos', 'Consolidado_23_Excel_repuestos.xlsx', 'Sistema INCAMAT', ?, ?, ?, 'Procesado')", [created, updated, areasMissing]);
  await conn.commit(); console.log(JSON.stringify({ codigos_unicos: masters.size, creados: created, actualizados: updated, relaciones_area: associations, areas_no_encontradas: areasMissing }));
} catch (error) { if (conn) await conn.rollback(); console.error(error); process.exitCode = 1; } finally { if (conn) conn.release(); await pool.end(); } })();
