import { useEffect, useMemo, useState } from "react";
import DashboardLayout from "../layouts/DashboardLayout";
import PageHeader from "../components/PageHeader";
import "../styles/anuncios.css";

const API = import.meta.env.VITE_API_URL || "/api";
const tokenHeaders = (json = false) => ({ ...(json ? { "Content-Type": "application/json" } : {}), Authorization: `Bearer ${localStorage.getItem("authToken") || ""}` });
const initial = { titulo: "", mensaje: "", destino: "Todos", id_area: "", prioridad: "Informativo", fecha_fin: "", estado: "Publicado" };
const accent = { Informativo: "info", Importante: "important", Urgente: "urgent" };
const displayRole = (role) => (["Tecnico", "Técnico", "TÃ©cnico", "T??cnico"].includes(role) ? "Técnico" : role);
const cleanText = (value) => String(value || "").replace(/T(\?\?|Ã©|�)cnico/gi, "Técnico");

function Anuncios() {
  const user = JSON.parse(localStorage.getItem("usuario") || "{}");
  const isAdmin = user.rol === "Administrador";
  const [items, setItems] = useState([]); const [areas, setAreas] = useState([]); const [open, setOpen] = useState(false);
  const [form, setForm] = useState(initial); const [filter, setFilter] = useState("Todos"); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { const response = await fetch(`${API}/anuncios`, { headers: tokenHeaders() }); const body = await response.json(); if (!response.ok) throw Error(body.error || "No fue posible cargar los anuncios."); setItems(body); };
  useEffect(() => { load().catch((error) => setMessage(error.message)); if (isAdmin) fetch(`${API}/areas`).then((r) => r.json()).then(setAreas).catch(() => setAreas([])); }, [isAdmin]);
  const visible = useMemo(() => filter === "Todos" ? items : items.filter((item) => item.prioridad === filter), [items, filter]);
  const create = async (event) => { event.preventDefault(); setSaving(true); setMessage(""); try { const estado = event.nativeEvent.submitter?.value || "Publicado"; const response = await fetch(`${API}/anuncios`, { method: "POST", headers: tokenHeaders(true), body: JSON.stringify({ ...form, estado, id_area: form.id_area || null }) }); const body = await response.json(); if (!response.ok) throw Error(body.error); setMessage(body.mensaje); setOpen(false); setForm(initial); await load(); } catch (error) { setMessage(error.message || "No fue posible guardar el anuncio."); } finally { setSaving(false); } };
  const changeState = async (id, estado) => { const response = await fetch(`${API}/anuncios/${id}`, { method: "PATCH", headers: tokenHeaders(true), body: JSON.stringify({ estado }) }); const body = await response.json(); setMessage(body.mensaje || body.error || ""); if (response.ok) load(); };
  const remove = async (id) => { if (!window.confirm("¿Eliminar este anuncio?")) return; const response = await fetch(`${API}/anuncios/${id}`, { method: "DELETE", headers: tokenHeaders() }); const body = await response.json(); setMessage(body.mensaje || body.error || ""); if (response.ok) load(); };
  const recipient = form.destino === "Todos" ? "todos los perfiles" : form.destino === "Tecnico" ? "técnicos" : "operarios";

  return <DashboardLayout>
    <PageHeader eyebrow="COMUNICACIÓN OPERATIVA" title="Panel de anuncios" description={isAdmin ? "Crea y envía avisos dirigidos al perfil y área que corresponda." : "Aquí aparecen únicamente los avisos dirigidos a tu perfil y área."} action={isAdmin ? <button className="button button-primary" onClick={() => { setForm(initial); setOpen(true); }}>+ Publicar anuncio</button> : null} />
    {message && <p className="announcement-toast">{message}</p>}
    <section className="announcement-hero"><div><span className="announcement-icon">◉</span><div><p className="eyebrow">BANDEJA PERSONALIZADA</p><h2>{isAdmin ? "Comunica cambios de forma segmentada" : `Avisos para ${cleanText(user.nombre) || displayRole(user.rol) || "tu equipo"}`}</h2><p>{isAdmin ? "Elige si el anuncio será visto por operarios, técnicos o toda la planta; también puedes dirigirlo a un área específica." : "Los avisos globales y los de tu área aparecen aquí automáticamente."}</p></div></div><aside><strong>{items.filter((item) => item.prioridad === "Urgente").length}</strong><span>urgentes</span></aside></section>
    <section className="announcement-controls"><div className="filter-group">{["Todos", "Urgente", "Importante", "Informativo"].map((priority) => <button key={priority} className={filter === priority ? "selected" : ""} onClick={() => setFilter(priority)}>{priority}</button>)}</div><p>{visible.length} aviso{visible.length === 1 ? "" : "s"} visible{visible.length === 1 ? "" : "s"}</p></section>
    <section className="announcement-grid">{visible.map((item) => <article className={`announcement-card ${accent[item.prioridad] || "info"}`} key={item.id}><header><span className="announcement-priority">{item.prioridad}</span><time>{new Date(item.publicado_en).toLocaleDateString("es-PE", { day: "2-digit", month: "short", year: "numeric" })}</time></header><h2>{item.titulo}</h2><p>{item.mensaje}</p><footer><span>◈ {item.area || "Toda la planta"}</span><span>◉ {item.destino === "Todos" ? "Todos los perfiles" : displayRole(item.destino)}</span><span>Por {item.publicado_por}</span></footer>{isAdmin && <div className="announcement-admin-actions"><button onClick={() => changeState(item.id, item.estado === "Publicado" ? "Archivado" : "Publicado")}>{item.estado === "Publicado" ? "Archivar" : "Publicar"}</button><button className="danger" onClick={() => remove(item.id)}>Eliminar</button></div>}</article>)}{!visible.length && <article className="announcement-empty"><span>✦</span><h2>No hay anuncios para mostrar</h2><p>{isAdmin ? "Publica un aviso para informar al equipo." : "Cuando el administrador publique un aviso para tu área, aparecerá aquí."}</p></article>}</section>
    {open && <div className="modal-backdrop"><form className="modal announcement-modal" onSubmit={create}><div className="modal-header"><div><p className="eyebrow">NUEVO ANUNCIO</p><h2>Publicar comunicación</h2><p>Define quién recibirá este aviso antes de publicarlo.</p></div><button type="button" onClick={() => setOpen(false)}>×</button></div><label>Título<input required maxLength="140" value={form.titulo} placeholder="Ej.: Mantenimiento programado" onChange={(event) => setForm({ ...form, titulo: event.target.value })} /></label><label>Mensaje<textarea required maxLength="1000" placeholder="Explica qué debe saber o hacer el equipo." value={form.mensaje} onChange={(event) => setForm({ ...form, mensaje: event.target.value })} /></label><div className="form-grid"><label>Enviar a<select value={form.destino} onChange={(event) => setForm({ ...form, destino: event.target.value })}><option value="Todos">Todos los perfiles</option><option value="Operario">Solo operarios</option><option value="Tecnico">Solo técnicos</option></select></label><label>Área destinataria<select value={form.id_area} onChange={(event) => setForm({ ...form, id_area: event.target.value })}><option value="">Toda la planta</option>{areas.map((area) => <option key={area.id} value={area.id}>{area.nombre}</option>)}</select></label><label>Prioridad<select value={form.prioridad} onChange={(event) => setForm({ ...form, prioridad: event.target.value })}><option>Informativo</option><option>Importante</option><option>Urgente</option></select></label><label>Visible hasta (opcional)<input type="date" value={form.fecha_fin} onChange={(event) => setForm({ ...form, fecha_fin: event.target.value })} /></label></div><div className="announcement-publish-note">Se enviará a <b>{recipient}</b> de <b>{areas.find((area) => String(area.id) === String(form.id_area))?.nombre || "toda la planta"}</b>.</div><div className="manual-machine-actions"><button type="submit" name="estado" value="Borrador" className="button button-secondary" disabled={saving}>Guardar borrador</button><button type="submit" name="estado" value="Publicado" className="button button-primary" disabled={saving}>{saving ? "Guardando..." : "Publicar anuncio"}</button></div></form></div>}
  </DashboardLayout>;
}

export default Anuncios;
