import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import DashboardLayout from "../layouts/DashboardLayout";
import PageHeader from "../components/PageHeader";
import StatusPill from "../components/StatusPill";
import { useIncaMant } from "../data/incamatData";
import { canManageAssets } from "../data/roles";
import "../styles/repuestos-pro.css";
import "../styles/movimientos-almacen.css";
import "../styles/clasificacion-repuestos.css";

const API = import.meta.env.VITE_API_URL || "/api";
const initialForm = { codigo: "", descripcion: "", unidad_medida: "unidad", ubicacion_almacen: "", criticidad: "Sin evaluar", stock_actual: 0, stock_minimo: 0, stock_verificado: false, frecuencia_solicitud: "Según falla" };
const blankMovement = { id_repuesto: "", tipo: "Entrada", cantidad: 1, stock_resultante: "", id_area: "", id_maquina: "", usuario: "", observaciones: "" };
const familyLabel = { Mecanico: "Mecánico", Electrico: "Eléctrico", Electronico: "Electrónico", Consumible: "Consumible", "Sin clasificar": "Sin clasificar" };
const stockState = (item) => !item.stockVerificado ? "Por verificar" : Number(item.stock) <= 0 ? "Sin stock" : Number(item.stock) <= Number(item.minimo) ? "Bajo mínimo" : "Disponible";
const criticalityWeight = { Crítica: 4, Alta: 3, Media: 2, Baja: 1, "Sin evaluar": 0 };
const elapsed = (date) => { if (!date) return "Sin historial"; const days = Math.max(0, Math.floor((Date.now() - new Date(`${date}T00:00:00`).getTime()) / 86400000)); return days === 0 ? "Hoy" : `Hace ${days} días`; };
const money = (value) => Number(value || 0).toLocaleString("es-PE", { style: "currency", currency: "PEN", maximumFractionDigits: 0 });

function Componentes() {
  const canEditInventory = canManageAssets();
  const { components, areas, machines, addComponent, refresh } = useIncaMant();
  const [search, setSearch] = useState("");
  const [areaFilter, setAreaFilter] = useState("Todas");
  const [familyFilter, setFamilyFilter] = useState("Todas");
  const [stockFilter, setStockFilter] = useState("Todos");
  const [criticality, setCriticality] = useState("Todos");
  const [sortBy, setSortBy] = useState("alerta");
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState(initialForm);
  const [classification, setClassification] = useState(null);
  const [classificationForm, setClassificationForm] = useState({ familia_tecnica: "Mecanico", subfamilia_tecnica: "", estado_clasificacion: "Validada" });
  const [criticalityItem, setCriticalityItem] = useState(null);
  const [criticalityForm, setCriticalityForm] = useState({ impacto_produccion: 3, tiempo_reposicion_nivel: 3, disponibilidad_alternativa: 3, impacto_economico: 3 });
  const [stockItem, setStockItem] = useState(null);
  const [stockForm, setStockForm] = useState({ stock_actual: 0, stock_minimo: 0, ubicacion_almacen: "", usuario: "" });
  const [movementOpen, setMovementOpen] = useState(false);
  const [movement, setMovement] = useState(blankMovement);
  const [movements, setMovements] = useState([]);
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);

  const loadMovements = async () => {
    const response = await fetch(`${API}/repuestos/movimientos`);
    if (!response.ok) throw Error("No fue posible cargar los movimientos.");
    setMovements(await response.json());
  };
  useEffect(() => { loadMovements().catch((requestError) => setError(requestError.message)); }, []);

  const metrics = useMemo(() => ({
    total: components.length,
    mechanical: components.filter((item) => item.familiaTecnica === "Mecanico").length,
    electrical: components.filter((item) => item.familiaTecnica === "Electrico").length,
    electronic: components.filter((item) => item.familiaTecnica === "Electronico").length,
    pending: components.filter((item) => item.estadoClasificacion !== "Validada").length,
  }), [components]);
  const areaCards = useMemo(() => areas.map((area) => ({ ...area, total: components.filter((item) => String(item.area || "").split(" · ").includes(area.nombre)).length })).filter((area) => area.total > 0).sort((a, b) => a.nombre.localeCompare(b.nombre, "es")), [areas, components]);
  const rows = useMemo(() => components.filter((item) => {
    const belongsToArea = areaFilter === "Todas" || String(item.area || "").split(" · ").includes(areaFilter);
    const matchesSearch = `${item.codigo} ${item.nombre} ${item.area}`.toLocaleLowerCase("es").includes(search.toLocaleLowerCase("es"));
    return belongsToArea && matchesSearch && (familyFilter === "Todas" || item.familiaTecnica === familyFilter) && (stockFilter === "Todos" || stockState(item) === stockFilter) && (criticality === "Todos" || item.criticidad === criticality);
  }).sort((a, b) => {
    if (sortBy === "familia") return String(a.familiaTecnica).localeCompare(String(b.familiaTecnica), "es") || a.nombre.localeCompare(b.nombre, "es");
    if (sortBy === "criticidad") return (criticalityWeight[b.criticidad] || 0) - (criticalityWeight[a.criticidad] || 0);
    if (sortBy === "solicitudes") return Number(b.solicitudes || 0) - Number(a.solicitudes || 0);
    const weights = { "Sin stock": 4, "Bajo mínimo": 3, "Por verificar": 2, Disponible: 1 };
    return weights[stockState(b)] - weights[stockState(a)] || a.nombre.localeCompare(b.nombre, "es");
  }), [components, areaFilter, search, familyFilter, stockFilter, criticality, sortBy]);
  const areaMachines = useMemo(() => machines.filter((machine) => !movement.id_area || String(machine.id_area) === String(movement.id_area)), [machines, movement.id_area]);

  const chooseArea = (name) => { setAreaFilter(name); setSearch(""); document.querySelector(".spare-workspace")?.scrollIntoView({ behavior: "smooth", block: "start" }); };
  const submitComponent = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { await addComponent(form); setForm(initialForm); setOpen(false); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const submitClassification = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(`${API}/repuestos/${classification.id}/clasificacion`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(classificationForm) }); const body = await response.json(); if (!response.ok) throw Error(body.error); setClassification(null); await refresh(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const submitMovement = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(`${API}/repuestos/movimientos`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(movement) }); const body = await response.json(); if (!response.ok) throw Error(body.error); setMovementOpen(false); setMovement(blankMovement); await Promise.all([refresh(), loadMovements()]); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const submitCriticality = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(`${API}/repuestos/${criticalityItem.id}/criticidad`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...criticalityForm, usuario: JSON.parse(localStorage.getItem("usuario") || "{}").nombre || "Administrador" }) }); const body = await response.json(); if (!response.ok) throw Error(body.error); setCriticalityItem(null); await refresh(); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };
  const submitStockVerification = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(`${API}/repuestos/${stockItem.id}/stock-verificado`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(stockForm) }); const body = await response.json(); if (!response.ok) throw Error(body.error); setStockItem(null); await Promise.all([refresh(), loadMovements()]); } catch (requestError) { setError(requestError.message); } finally { setSaving(false); } };

  return <DashboardLayout>
    <PageHeader eyebrow="ALMACÉN TÉCNICO" title="Repuestos" description="Clasifica y controla el inventario técnico antes de evaluar su criticidad." action={<><Link className="button button-secondary" to="/solicitudes">Ver solicitudes</Link>{canEditInventory && <><Link className="button button-secondary" to="/importaciones?modulo=Repuestos">Importar Excel</Link><button className="button button-primary" onClick={() => setMovementOpen(true)}>+ Registrar movimiento</button><button className="button button-secondary" onClick={() => setOpen(true)}>+ Nuevo repuesto</button></>}</>} />
    <section className="classification-metrics"><article><span>Catálogo</span><strong>{metrics.total}</strong><small>Repuestos registrados</small></article><article className="mechanical"><span>Mecánicos</span><strong>{metrics.mechanical}</strong><small>Transmisión, estructura y movimiento</small></article><article className="electrical"><span>Eléctricos</span><strong>{metrics.electrical}</strong><small>Potencia, control y conexiones</small></article><article className="electronic"><span>Electrónicos</span><strong>{metrics.electronic}</strong><small>Sensores, PLC, tarjetas y variadores</small></article><article className="pending"><span>Por validar</span><strong>{metrics.pending}</strong><small>Requieren revisión técnica</small></article></section>
    <section className="spare-area-navigation"><header><div><p className="eyebrow">REPUESTOS POR ÁREA</p><h2>Ingresa al catálogo de tu área</h2><p>Selecciona una tarjeta para ver únicamente los repuestos vinculados a esa área.</p></div>{areaFilter !== "Todas" && <button type="button" className="button button-secondary" onClick={() => chooseArea("Todas")}>Ver todas las áreas</button>}</header><div className="area-card-grid">{areaCards.map((area) => <button type="button" key={area.id} className={`area-spare-card ${areaFilter === area.nombre ? "selected" : ""}`} onClick={() => chooseArea(area.nombre)}><span>ÁREA OPERATIVA</span><strong>{area.nombre}</strong><small>{area.total} repuestos asociados</small><b>Ver repuestos →</b></button>)}</div></section>
    <section className="spare-workspace"><header><div><p className="eyebrow">CLASIFICACIÓN TÉCNICA</p><h2>{areaFilter === "Todas" ? "Ordena el catálogo por especialidad" : `Repuestos de ${areaFilter}`}</h2><p>{areaFilter === "Todas" ? "Filtra por familia, stock y criticidad." : "Catálogo filtrado por el área seleccionada."}</p></div><strong>{rows.length} resultados</strong></header><div className="spare-controls"><label className="spare-search"><span>Buscar repuesto</span><input placeholder="Código o descripción..." value={search} onChange={(event) => setSearch(event.target.value)} /></label><label><span>Estado de stock</span><select value={stockFilter} onChange={(event) => setStockFilter(event.target.value)}><option>Todos</option><option>Sin stock</option><option>Bajo mínimo</option><option>Por verificar</option><option>Disponible</option></select></label><label><span>Familia técnica</span><select value={familyFilter} onChange={(event) => setFamilyFilter(event.target.value)}><option>Todas</option><option>Mecanico</option><option>Electrico</option><option>Electronico</option><option>Consumible</option></select></label><label><span>Ordenar por</span><select value={sortBy} onChange={(event) => setSortBy(event.target.value)}><option value="alerta">Estado de alerta</option><option value="familia">Familia técnica</option><option value="criticidad">Mayor criticidad</option><option value="solicitudes">Más solicitado</option></select></label></div><div className="criticality-filter"><span>Criticidad</span>{["Todos", "Sin evaluar", "Crítica", "Alta", "Media", "Baja"].map((item) => <button type="button" onClick={() => setCriticality(item)} className={criticality === item ? "selected" : ""} key={item}>{item}</button>)}</div></section>
    <section className="panel table-panel spare-table"><table><thead><tr><th>Repuesto</th><th>Familia técnica</th><th>Áreas / unidad</th><th>Criticidad</th><th>Control de stock</th><th>Solicitud y costo</th><th>Estado</th></tr></thead><tbody>{rows.map((item) => { const state = stockState(item); return <tr key={item.id}><td><strong>{item.nombre}</strong><small className="code">{item.codigo}</small></td><td><button className={`classification-chip ${String(item.estadoClasificacion).toLocaleLowerCase("es")}`} onClick={() => { setClassification(item); setClassificationForm({ familia_tecnica: item.familiaTecnica === "Sin clasificar" ? "Mecanico" : item.familiaTecnica, subfamilia_tecnica: item.subfamiliaTecnica || "", estado_clasificacion: item.estadoClasificacion || "Sugerida" }); }}>{familyLabel[item.familiaTecnica]}</button><small>{item.subfamiliaTecnica || item.estadoClasificacion}</small></td><td>{item.area}<small>{item.unidad || "unidad"}</small></td><td><StatusPill value={item.criticidad} /><small>{item.puntajeCriticidad == null ? "Pendiente de evaluación" : `Puntaje: ${item.puntajeCriticidad}/20`}</small><button className="table-action" onClick={() => { setCriticalityItem(item); setCriticalityForm({ impacto_produccion: item.impactoProduccion || 3, tiempo_reposicion_nivel: item.reposicionNivel || 3, disponibilidad_alternativa: item.alternativaNivel || 3, impacto_economico: item.impactoEconomico || 3 }); }}>{item.puntajeCriticidad == null ? "Evaluar" : "Revisar"}</button></td><td><strong className={state === "Sin stock" || state === "Bajo mínimo" ? "stock-low" : ""}>{item.stock}</strong><small>{item.stockVerificado ? `Verificado por ${item.stockVerificadoPor || "almacén"}` : "Pendiente de verificar"}</small><button className="table-action" onClick={() => { setStockItem(item); setStockForm({ stock_actual: item.stock, stock_minimo: item.minimo, ubicacion_almacen: item.ubicacionAlmacen || "", usuario: JSON.parse(localStorage.getItem("usuario") || "{}").nombre || "" }); }}>{item.stockVerificado ? "Recontar" : "Verificar"}</button></td><td><strong>{item.ultimaSolicitud || "Sin fecha"}</strong><small>{elapsed(item.ultimaSolicitud)} · {item.solicitudes || 0} pedidos</small><small>Costo último: {money(item.costoUltimo)}</small></td><td><span className={`stock-state ${state.toLocaleLowerCase("es").replaceAll(" ", "-")}`}>{state}</span></td></tr>; })}{!rows.length && <tr><td colSpan="7" className="empty-state">No hay repuestos asociados a estos filtros.</td></tr>}</tbody></table></section>
    <section className="movement-history"><header><div><p className="eyebrow">TRAZABILIDAD DE ALMACÉN</p><h2>Últimos movimientos</h2></div><button className="button button-secondary" onClick={() => loadMovements().catch((requestError) => setError(requestError.message))}>Actualizar</button></header><div className="panel table-panel"><table><thead><tr><th>Fecha / vale</th><th>Tipo</th><th>Repuesto</th><th>Cantidad</th><th>Destino</th><th>Responsable</th></tr></thead><tbody>{movements.slice(0, 12).map((item) => <tr key={item.id}><td><strong>{String(item.fecha_movimiento).slice(0, 10)}</strong><small className="code">{item.numero_vale}</small></td><td>{item.estado}</td><td><strong>{item.descripcion}</strong><small>{item.codigo}</small></td><td>{item.cantidad}</td><td>{item.area || "Almacén"}<small>{item.maquina || "Sin máquina"}</small></td><td>{item.autorizado_por}</td></tr>)}{!movements.length && <tr><td colSpan="6" className="empty-state">Aún no hay movimientos registrados.</td></tr>}</tbody></table></div></section>
    {error && <p className="form-error">{error}</p>}
    {criticalityItem && <div className="modal-backdrop"><form className="modal criticality-modal" onSubmit={submitCriticality}><div className="modal-header"><div><p className="eyebrow">MATRIZ DE CRITICIDAD</p><h2>Evaluar {criticalityItem.nombre}</h2><p>Califica de 1 (bajo) a 5 (alto). La aplicación calcula la prioridad final.</p></div><button type="button" onClick={() => setCriticalityItem(null)}>×</button></div><div className="criticality-guide"><span>4–8: Baja</span><span>9–12: Media</span><span>13–16: Alta</span><span>17–20: Crítica</span></div><div className="form-grid"><label>Impacto en producción<select value={criticalityForm.impacto_produccion} onChange={(event) => setCriticalityForm({ ...criticalityForm, impacto_produccion: event.target.value })}>{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value} · {value === 1 ? "Sin parada" : value === 5 ? "Detiene producción" : "Impacto intermedio"}</option>)}</select></label><label>Tiempo de reposición<select value={criticalityForm.tiempo_reposicion_nivel} onChange={(event) => setCriticalityForm({ ...criticalityForm, tiempo_reposicion_nivel: event.target.value })}>{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value} · {value === 1 ? "Disponible local" : value === 5 ? "Importación / largo plazo" : "Tiempo intermedio"}</option>)}</select></label><label>Alternativa disponible<select value={criticalityForm.disponibilidad_alternativa} onChange={(event) => setCriticalityForm({ ...criticalityForm, disponibilidad_alternativa: event.target.value })}>{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value} · {value === 1 ? "Reemplazo fácil" : value === 5 ? "Sin reemplazo" : "Alternativa limitada"}</option>)}</select></label><label>Impacto económico<select value={criticalityForm.impacto_economico} onChange={(event) => setCriticalityForm({ ...criticalityForm, impacto_economico: event.target.value })}>{[1,2,3,4,5].map((value) => <option key={value} value={value}>{value} · {value === 1 ? "Costo bajo" : value === 5 ? "Costo muy alto" : "Costo intermedio"}</option>)}</select></label></div><button className="button button-primary" disabled={saving}>{saving ? "Guardando..." : "Calcular y validar criticidad"}</button></form></div>}
    {stockItem && <div className="modal-backdrop"><form className="modal" onSubmit={submitStockVerification}><div className="modal-header"><div><p className="eyebrow">INVENTARIO FÍSICO</p><h2>Verificar stock</h2><p>{stockItem.codigo} · {stockItem.nombre}</p></div><button type="button" onClick={() => setStockItem(null)}>×</button></div><label>Stock físico contado<input required type="number" min="0" step="0.01" value={stockForm.stock_actual} onChange={(event) => setStockForm({ ...stockForm, stock_actual: event.target.value })} /></label><label>Stock mínimo<input required type="number" min="0" step="0.01" value={stockForm.stock_minimo} onChange={(event) => setStockForm({ ...stockForm, stock_minimo: event.target.value })} /></label><label>Ubicación en almacén<input required value={stockForm.ubicacion_almacen} placeholder="Ej.: Almacén central · Rack A-03" onChange={(event) => setStockForm({ ...stockForm, ubicacion_almacen: event.target.value })} /></label><label>Responsable de conteo<input required value={stockForm.usuario} onChange={(event) => setStockForm({ ...stockForm, usuario: event.target.value })} /></label><p className="helper-text">Si el conteo cambia el stock, se genera un ajuste con trazabilidad.</p><button className="button button-primary" disabled={saving}>{saving ? "Guardando..." : "Confirmar inventario físico"}</button></form></div>}
    {classification && <div className="modal-backdrop"><form className="modal classification-modal" onSubmit={submitClassification}><div className="modal-header"><div><h2>Clasificar repuesto</h2><p>{classification.codigo} · {classification.nombre}</p></div><button type="button" onClick={() => setClassification(null)}>×</button></div><label>Familia técnica<select value={classificationForm.familia_tecnica} onChange={(event) => setClassificationForm({ ...classificationForm, familia_tecnica: event.target.value })}><option value="Mecanico">Mecánico</option><option value="Electrico">Eléctrico</option><option value="Electronico">Electrónico</option><option value="Consumible">Consumible</option></select></label><label>Subfamilia técnica<input required value={classificationForm.subfamilia_tecnica} onChange={(event) => setClassificationForm({ ...classificationForm, subfamilia_tecnica: event.target.value })} /></label><label>Estado<select value={classificationForm.estado_clasificacion} onChange={(event) => setClassificationForm({ ...classificationForm, estado_clasificacion: event.target.value })}><option>Pendiente</option><option>Sugerida</option><option>Validada</option></select></label><button className="button button-primary" disabled={saving}>Guardar clasificación</button></form></div>}
    {movementOpen && <div className="modal-backdrop"><form className="modal modal-wide movement-modal" onSubmit={submitMovement}><div className="modal-header"><div><h2>Registrar movimiento de almacén</h2><p>Las salidas quedan vinculadas al área que recibe el repuesto.</p></div><button type="button" onClick={() => setMovementOpen(false)}>×</button></div><div className="movement-type-choice">{["Entrada", "Salida", "Ajuste"].map((type) => <button type="button" key={type} onClick={() => setMovement({ ...movement, tipo: type })} className={movement.tipo === type ? "selected" : ""}>{type}</button>)}</div><div className="form-grid"><label>Repuesto<select required value={movement.id_repuesto} onChange={(event) => setMovement({ ...movement, id_repuesto: event.target.value })}><option value="">Seleccionar</option>{components.map((item) => <option value={item.id} key={item.id}>{item.codigo} · {item.nombre}</option>)}</select></label><label>Responsable<input required value={movement.usuario} onChange={(event) => setMovement({ ...movement, usuario: event.target.value })} /></label>{movement.tipo === "Ajuste" ? <label>Stock físico contado<input required type="number" min="0" value={movement.stock_resultante} onChange={(event) => setMovement({ ...movement, stock_resultante: event.target.value })} /></label> : <label>Cantidad<input required type="number" min="0.01" step="0.01" value={movement.cantidad} onChange={(event) => setMovement({ ...movement, cantidad: event.target.value })} /></label>}{movement.tipo === "Salida" && <><label>Área que recibe<select required value={movement.id_area} onChange={(event) => setMovement({ ...movement, id_area: event.target.value, id_maquina: "" })}><option value="">Seleccionar</option>{areas.map((area) => <option value={area.id} key={area.id}>{area.nombre}</option>)}</select></label><label>Máquina (opcional)<select value={movement.id_maquina} onChange={(event) => setMovement({ ...movement, id_maquina: event.target.value })}><option value="">No aplica</option>{areaMachines.map((machine) => <option value={machine.id} key={machine.id}>{machine.nombre}</option>)}</select></label></>}</div><label>Motivo u observación<textarea value={movement.observaciones} onChange={(event) => setMovement({ ...movement, observaciones: event.target.value })} /></label><button className="button button-primary" disabled={saving}>Registrar {movement.tipo.toLowerCase()}</button></form></div>}
    {open && <div className="modal-backdrop"><form className="modal modal-wide" onSubmit={submitComponent}><div className="modal-header"><div><h2>Registrar repuesto</h2><p>También podrás crearlo desde Excel.</p></div><button type="button" onClick={() => setOpen(false)}>×</button></div><div className="form-grid"><label>Código<input required value={form.codigo} onChange={(event) => setForm({ ...form, codigo: event.target.value })} /></label><label>Descripción<input required value={form.descripcion} onChange={(event) => setForm({ ...form, descripcion: event.target.value })} /></label><label>Unidad<input value={form.unidad_medida} onChange={(event) => setForm({ ...form, unidad_medida: event.target.value })} /></label><label>Ubicación de almacén<input value={form.ubicacion_almacen} onChange={(event) => setForm({ ...form, ubicacion_almacen: event.target.value })} /></label><label>Criticidad<select value={form.criticidad} onChange={(event) => setForm({ ...form, criticidad: event.target.value })}><option>Sin evaluar</option><option>Crítica</option><option>Alta</option><option>Media</option><option>Baja</option></select></label><label>Stock actual<input type="number" min="0" value={form.stock_actual} onChange={(event) => setForm({ ...form, stock_actual: event.target.value })} /></label><label>Stock mínimo<input type="number" min="0" value={form.stock_minimo} onChange={(event) => setForm({ ...form, stock_minimo: event.target.value })} /></label></div><label className="checkbox-label"><input type="checkbox" checked={form.stock_verificado} onChange={(event) => setForm({ ...form, stock_verificado: event.target.checked })} /> Stock físico verificado</label><button className="button button-primary" disabled={saving}>Guardar repuesto</button></form></div>}
  </DashboardLayout>;
}

export default Componentes;
