import { useCallback, useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import DashboardLayout from "../layouts/DashboardLayout";
import PageHeader from "../components/PageHeader";
import { useIncaMant } from "../data/incamatData";
import { canManageAssets } from "../data/roles";
import "../styles/locations-tree.css";

const API_URL = import.meta.env.VITE_API_URL || "/api";
const emptyMachine = (areaId = "") => ({ codigo: "", nombre: "", id_area: String(areaId), marca: "", modelo: "", descripcion_corta: "", estado: "Operativa" });
const emptyArea = { codigo: "", nombre: "", descripcion: "", responsable: "" };

function Localizaciones() {
  const canEdit = canManageAssets();
  const { areas, loading, addMachine, refresh } = useIncaMant();
  // La vista principal muestra solamente áreas que ya tienen equipos asignados.
  // Las áreas nuevas siguen disponibles para registrar máquinas, pero no ocupan
  // una tarjeta hasta que tengan al menos un equipo.
  const visibleAreas = useMemo(() => areas.filter((area) => area.nombre !== "Sin clasificar" && Number(area.maquinas || 0) > 0), [areas]);
  const [selectedId, setSelectedId] = useState(null); const [machines, setMachines] = useState([]); const [selectedMachine, setSelectedMachine] = useState(null);
  const [machineOpen, setMachineOpen] = useState(false); const [areaOpen, setAreaOpen] = useState(false); const [saving, setSaving] = useState(false); const [formError, setFormError] = useState("");
  const [machineForm, setMachineForm] = useState(emptyMachine()); const [areaForm, setAreaForm] = useState(emptyArea);
  const loadMachines = useCallback(async (areaId) => { if (!areaId) return; try { const response = await fetch(`${API_URL}/areas/${areaId}/maquinas`); setMachines(response.ok ? await response.json() : []); } catch { setMachines([]); } }, []);
  useEffect(() => { if (!selectedId && visibleAreas[0]) setSelectedId(visibleAreas[0].id); }, [visibleAreas, selectedId]);
  useEffect(() => { loadMachines(selectedId); }, [loadMachines, selectedId]);
  const selectedArea = areas.find((area) => String(area.id) === String(selectedId));
  const openMachine = () => { setFormError(""); setMachineForm(emptyMachine(selectedId || visibleAreas[0]?.id || "")); setMachineOpen(true); };
  const saveMachine = async (event) => { event.preventDefault(); const targetArea = areas.find((area) => String(area.id) === String(machineForm.id_area)); if (!targetArea) return setFormError("Selecciona un área válida."); setSaving(true); setFormError(""); try { await addMachine({ ...machineForm, area: targetArea.nombre }); setSelectedId(targetArea.id); await loadMachines(targetArea.id); setMachineOpen(false); } catch (error) { setFormError(error.message || "No fue posible registrar la máquina."); } finally { setSaving(false); } };
  const saveArea = async (event) => { event.preventDefault(); setSaving(true); setFormError(""); try { const response = await fetch(`${API_URL}/areas`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(areaForm) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "No fue posible registrar el área."); await refresh(); setSelectedId(body.id); setAreaForm(emptyArea); setAreaOpen(false); } catch (error) { setFormError(error.message || "No fue posible registrar el área."); } finally { setSaving(false); } };
  if (loading || !selectedArea) return <DashboardLayout><p className="empty-state">Cargando áreas de planta...</p></DashboardLayout>;
  return <DashboardLayout><PageHeader eyebrow="ORGANIZACIÓN DE PLANTA" title="Áreas" description="Selecciona un área para consultar únicamente las máquinas que le pertenecen." action={canEdit ? <div className="location-header-actions"><Link className="button button-secondary" to="/importaciones?modulo=Areas">Importar Excel</Link><button className="button button-primary" onClick={() => { setFormError(""); setAreaOpen(true); }}>+ Añadir área</button></div> : null} />
    <section className="areas-intro"><strong>{visibleAreas.length}</strong><div><h2>Áreas oficiales de Incalpaca</h2><p>Las máquinas se organizan por el área a la que pertenecen.</p></div></section>
    <section className="area-selector"><h2>Selecciona un área</h2><div className="area-selector-grid">{visibleAreas.map((area) => <button className={String(area.id) === String(selectedId) ? "area-select-card active" : "area-select-card"} key={area.id} onClick={() => setSelectedId(area.id)}><strong>{area.nombre}</strong><span>{area.maquinas} máquinas</span><b>{String(area.id) === String(selectedId) ? "Mostrando" : "Ver máquinas →"}</b></button>)}</div></section>
    <section className="area-machines-panel"><header><div><p className="eyebrow">ÁREA SELECCIONADA</p><h2>{selectedArea.nombre}</h2><p>{machines.length} máquinas registradas en esta área.</p></div>{canEdit && <button className="button button-secondary area-add-button" onClick={openMachine}>+ Añadir máquina a esta área</button>}</header>{machines.length ? <div className="location-machine-grid">{machines.map((machine) => <button className="location-machine-card" key={machine.id} onClick={() => setSelectedMachine(machine)}><span>▣</span><div><strong>{machine.nombre}</strong><small>{machine.marca || "Sin marca"}</small><em>{machine.modelo || "Sin modelo"}</em></div><b>Ver ficha →</b></button>)}</div> : <p className="empty-state">Aún no hay máquinas registradas en esta área.</p>}</section>
    {areaOpen && <div className="modal-backdrop"><form className="modal manual-area-modal" onSubmit={saveArea}><div className="modal-header"><div><p className="eyebrow">ORGANIZACIÓN DE PLANTA</p><h2>Añadir área</h2><p>Crea el área primero. Luego podrás asignarle máquinas y repuestos.</p></div><button type="button" onClick={() => setAreaOpen(false)}>×</button></div><label>Código del área<input required maxLength="30" placeholder="Ej.: AREA-PRODUCCION" value={areaForm.codigo} onChange={(event) => setAreaForm({ ...areaForm, codigo: event.target.value })} /></label><label>Nombre del área<input required maxLength="100" placeholder="Ej.: Producción especial" value={areaForm.nombre} onChange={(event) => setAreaForm({ ...areaForm, nombre: event.target.value })} /></label><label>Responsable<input maxLength="120" placeholder="Opcional" value={areaForm.responsable} onChange={(event) => setAreaForm({ ...areaForm, responsable: event.target.value })} /></label><label>Descripción<input maxLength="255" placeholder="Función o alcance del área (opcional)" value={areaForm.descripcion} onChange={(event) => setAreaForm({ ...areaForm, descripcion: event.target.value })} /></label>{formError && <p className="manual-machine-error">{formError}</p>}<div className="manual-machine-actions"><button type="button" className="button button-secondary" onClick={() => setAreaOpen(false)}>Cancelar</button><button className="button button-primary" disabled={saving}>{saving ? "Guardando..." : "Guardar área"}</button></div></form></div>}
    {machineOpen && <div className="modal-backdrop"><form className="modal modal-wide manual-machine-modal" onSubmit={saveMachine}><div className="modal-header"><div><p className="eyebrow">REGISTRO MANUAL</p><h2>Añadir máquina</h2><p>Completa la ficha básica y asígnala a su área de trabajo.</p></div><button type="button" onClick={() => setMachineOpen(false)}>×</button></div><div className="manual-machine-note">La máquina quedará disponible de inmediato en el área seleccionada y en su ficha QR.</div><div className="form-grid"><label>Área<select required value={machineForm.id_area} onChange={(event) => setMachineForm({ ...machineForm, id_area: event.target.value })}>{visibleAreas.map((area) => <option key={area.id} value={area.id}>{area.nombre}</option>)}</select></label><label>Código interno<input required maxLength="50" placeholder="Ej.: M-CTP-001" value={machineForm.codigo} onChange={(event) => setMachineForm({ ...machineForm, codigo: event.target.value })} /></label><label>Nombre de la máquina<input required maxLength="150" placeholder="Ej.: Máquina de corte 01" value={machineForm.nombre} onChange={(event) => setMachineForm({ ...machineForm, nombre: event.target.value })} /></label><label>Estado<select value={machineForm.estado} onChange={(event) => setMachineForm({ ...machineForm, estado: event.target.value })}><option>Operativa</option><option>Mantenimiento</option><option>Detenida</option></select></label><label>Marca<input maxLength="100" placeholder="Opcional" value={machineForm.marca} onChange={(event) => setMachineForm({ ...machineForm, marca: event.target.value })} /></label><label>Modelo<input maxLength="100" placeholder="Opcional" value={machineForm.modelo} onChange={(event) => setMachineForm({ ...machineForm, modelo: event.target.value })} /></label></div><label>Descripción corta<input maxLength="280" placeholder="Función principal o referencia breve (opcional)" value={machineForm.descripcion_corta} onChange={(event) => setMachineForm({ ...machineForm, descripcion_corta: event.target.value })} /></label>{formError && <p className="manual-machine-error">{formError}</p>}<div className="manual-machine-actions"><button type="button" className="button button-secondary" onClick={() => setMachineOpen(false)}>Cancelar</button><button className="button button-primary" disabled={saving}>{saving ? "Guardando..." : "Guardar máquina"}</button></div></form></div>}
    {selectedMachine && <div className="modal-backdrop"><section className="modal machine-detail"><div className="modal-header"><div><p className="eyebrow">FICHA DE MÁQUINA</p><h2>{selectedMachine.nombre}</h2></div><button onClick={() => setSelectedMachine(null)}>×</button></div><p>{selectedMachine.descripcion_corta || `Equipo asignado a ${selectedArea.nombre}.`}</p><dl><div><dt>Área</dt><dd>{selectedArea.nombre}</dd></div><div><dt>Código interno</dt><dd>{selectedMachine.codigo}</dd></div><div><dt>Marca</dt><dd>{selectedMachine.marca || "Sin registro"}</dd></div><div><dt>Modelo</dt><dd>{selectedMachine.modelo || "Sin registro"}</dd></div><div><dt>Estado</dt><dd>{selectedMachine.estado}</dd></div></dl></section></div>}
  </DashboardLayout>;
}
export default Localizaciones;
