import { useEffect, useMemo, useState } from "react";
import DashboardLayout from "../layouts/DashboardLayout";
import PageHeader from "../components/PageHeader";
import StatusPill from "../components/StatusPill";
import { useIncaMant } from "../data/incamatData";
import "../styles/solicitudes.css";

const API = import.meta.env.VITE_API_URL || "/api";
const empty = { id_area: "", id_maquina: "", id_repuesto: "", cantidad_solicitada: 1, prioridad: "Media", motivo: "", solicitado_por: "" };
const normalize = (value) => String(value || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("es").trim();
const areaLabel = (area) => area.nombre;
const machineLabel = (machine) => `${machine.nombre} — ${machine.area || "Sin área"}`;
const spareLabel = (part) => `${part.codigo} — ${part.nombre}`;

function SearchPicker({ label, placeholder, query, setQuery, items, getLabel, onPick, required = false, emptyText, helper }) {
  const matches = items.filter((item) => !query || normalize(getLabel(item)).includes(normalize(query))).slice(0, 7);
  return <label className="search-picker"><span>{label}</span><input required={required} value={query} onChange={(event) => setQuery(event.target.value)} placeholder={placeholder} autoComplete="off" /><div className="search-picker-results">{matches.length ? matches.map((item) => <button type="button" key={item.id} onClick={() => onPick(item)}><strong>{getLabel(item)}</strong><small>Seleccionar</small></button>) : <p>{emptyText}</p>}</div>{helper && <small className="search-picker-help">{helper}</small>}</label>;
}

function Solicitudes() {
  const { areas, machines, components, refresh } = useIncaMant();
  const [items, setItems] = useState([]); const [indicators, setIndicators] = useState(null);
  const [open, setOpen] = useState(false); const [form, setForm] = useState(empty); const [filter, setFilter] = useState("Todas"); const [error, setError] = useState("");
  const [areaSearch, setAreaSearch] = useState(""); const [machineSearch, setMachineSearch] = useState(""); const [spareSearch, setSpareSearch] = useState("");
  const user = JSON.parse(localStorage.getItem("usuario") || "{}");
  const load = async () => { const [requests, metrics] = await Promise.all([fetch(`${API}/solicitudes`), fetch(`${API}/solicitudes/indicadores`)]); setItems(await requests.json()); setIndicators(await metrics.json()); };
  useEffect(() => { load().catch(() => setError("No se pudo cargar el módulo de solicitudes.")); }, []);

  const selectedArea = areas.find((area) => String(area.id) === String(form.id_area));
  const areaMachines = useMemo(() => machines.filter((machine) => !form.id_area || String(machine.id_area) === String(form.id_area)), [machines, form.id_area]);
  const associatedParts = useMemo(() => components.filter((item) => selectedArea && normalize(item.area).includes(normalize(selectedArea.nombre))), [components, selectedArea]);
  const availableParts = associatedParts.length ? associatedParts : components;
  const visible = items.filter((item) => filter === "Todas" || item.estado === filter);
  const summary = indicators?.resumen || { total: 0, pendientes: 0, aprobadas: 0, entregadas: 0 };
  const activeAreas = areas.filter((area) => Number(area.maquinas) > 0);

  const openRequest = () => { setError(""); setForm({ ...empty, solicitado_por: user.nombre || user.usuario || "" }); setAreaSearch(""); setMachineSearch(""); setSpareSearch(""); setOpen(true); };
  const pickArea = (area) => { setAreaSearch(areaLabel(area)); setMachineSearch(""); setSpareSearch(""); setForm({ ...form, id_area: area.id, id_maquina: "", id_repuesto: "" }); };
  const pickMachine = (machine) => { const machineArea = areas.find((area) => String(area.id) === String(machine.id_area)); setMachineSearch(machineLabel(machine)); setSpareSearch(""); setAreaSearch(machineArea ? areaLabel(machineArea) : areaSearch); setForm({ ...form, id_area: machine.id_area, id_maquina: machine.id, id_repuesto: "" }); };
  const pickSpare = (part) => { setSpareSearch(spareLabel(part)); setForm({ ...form, id_repuesto: part.id }); };
  const submit = async (event) => { event.preventDefault(); setError(""); if (!form.id_area) return setError("Selecciona un área desde las sugerencias."); if (!form.id_repuesto) return setError("Selecciona un repuesto desde las sugerencias."); const response = await fetch(`${API}/solicitudes`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) return setError(body.error); setOpen(false); setForm(empty); await load(); };
  const change = async (id, estado) => { const observacion_decision = estado === "Rechazada" ? window.prompt("Indica el motivo del rechazo:") : ""; if (estado === "Rechazada" && !observacion_decision) return; const response = await fetch(`${API}/solicitudes/${id}/estado`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ estado, usuario: user.nombre || user.usuario || "Administrador", observacion_decision }) }); const body = await response.json(); if (!response.ok) return setError(body.error); await Promise.all([load(), refresh()]); };

  return <DashboardLayout><PageHeader eyebrow="CONTROL DE ABASTECIMIENTO" title="Solicitudes de repuestos" description="Flujo trazable entre área solicitante, aprobación y entrega de almacén." action={<><a className="button button-secondary" href={`${API}/solicitudes/reporte.csv`}>Descargar CSV</a><button className="button button-primary" onClick={openRequest}>+ Nueva solicitud</button></>} />
    <section className="request-flow"><span><b>1</b> Área solicita</span><i>→</i><span><b>2</b> Supervisor aprueba</span><i>→</i><span><b>3</b> Almacén entrega</span><i>→</i><span><b>4</b> Stock actualizado</span></section>
    <section className="request-metrics"><div><strong>{summary.total}</strong><span>Solicitudes totales</span></div><div><strong>{summary.pendientes}</strong><span>Por aprobar</span></div><div><strong>{summary.aprobadas}</strong><span>Listas para entrega</span></div><div><strong>{summary.entregadas}</strong><span>Entregadas</span></div></section>
    <section className="request-insights"><article className="panel"><h2>Áreas que más solicitan</h2>{(indicators?.por_area || []).length ? indicators.por_area.map((row, index) => <div className="insight-row" key={row.nombre}><b>{index + 1}</b><strong>{row.nombre}</strong><span>{row.solicitudes} solicitudes · {row.cantidad} unidades</span></div>) : <p className="empty-state">Aún no hay solicitudes registradas.</p>}</article><article className="panel"><h2>Repuestos más solicitados</h2>{(indicators?.por_repuesto || []).length ? indicators.por_repuesto.map((row, index) => <div className="insight-row" key={row.codigo}><b>{index + 1}</b><strong>{row.descripcion}</strong><span>{row.solicitudes} solicitudes · {row.cantidad} unidades</span></div>) : <p className="empty-state">Se mostrará al registrar solicitudes.</p>}</article></section>
    <section className="toolbar"><div className="filter-group">{["Todas", "Solicitada", "Aprobada", "Entregada", "Rechazada"].map((state) => <button key={state} className={filter === state ? "selected" : ""} onClick={() => setFilter(state)}>{state}</button>)}</div></section>{error && <p className="form-error">{error}</p>}
    <section className="panel table-panel"><table><thead><tr><th>Número</th><th>Área / máquina</th><th>Repuesto</th><th>Cantidad</th><th>Prioridad</th><th>Solicitante</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{visible.map((item) => <tr key={item.id}><td><strong>{item.numero}</strong><small>{String(item.fecha_solicitud).slice(0, 10)}</small></td><td><strong>{item.area}</strong><small>{item.maquina || "Sin máquina asociada"}</small></td><td><strong>{item.repuesto}</strong><small>{item.codigo_repuesto} · {item.stock_verificado ? `stock ${item.stock_actual}` : "stock por verificar"}</small></td><td>{item.cantidad_solicitada}</td><td><StatusPill value={item.prioridad} /><small>{item.criticidad_repuesto}</small></td><td>{item.solicitado_por}</td><td><StatusPill value={item.estado} /></td><td className="request-actions">{item.estado === "Solicitada" ? <><button className="button button-secondary" onClick={() => change(item.id, "Aprobada")}>Aprobar</button><button className="button button-danger" onClick={() => change(item.id, "Rechazada")}>Rechazar</button></> : item.estado === "Aprobada" ? <button className="button button-primary" onClick={() => change(item.id, "Entregada")}>Entregar</button> : "—"}</td></tr>)}{!visible.length && <tr><td colSpan="8" className="empty-state">No hay solicitudes con este estado.</td></tr>}</tbody></table></section>
    {open && <div className="modal-backdrop"><form className="modal modal-wide request-form" onSubmit={submit}><div className="modal-header"><div><h2>Nueva solicitud de repuesto</h2><p>Escribe y elige la opción que aparece debajo. Así se guardan los códigos correctos.</p></div><button type="button" onClick={() => setOpen(false)} aria-label="Cerrar">×</button></div><div className="request-search-hint">Las opciones ya son visibles: presiona una para seleccionarla. Puedes escribir una parte del área, máquina, código o nombre del repuesto.</div><div className="form-grid"><SearchPicker label="Área solicitante" required placeholder="Escribe un área..." query={areaSearch} setQuery={(value) => { setAreaSearch(value); setForm({ ...form, id_area: "", id_maquina: "", id_repuesto: "" }); setMachineSearch(""); setSpareSearch(""); }} items={activeAreas} getLabel={areaLabel} onPick={pickArea} emptyText="No se encontró un área." /><SearchPicker label="Máquina (opcional)" placeholder="Escribe una máquina..." query={machineSearch} setQuery={(value) => { setMachineSearch(value); setForm({ ...form, id_maquina: "" }); }} items={form.id_area ? areaMachines : machines} getLabel={machineLabel} onPick={pickMachine} emptyText="No se encontró una máquina." /><SearchPicker label="Repuesto" required placeholder="Código o nombre del repuesto..." query={spareSearch} setQuery={(value) => { setSpareSearch(value); setForm({ ...form, id_repuesto: "" }); }} items={availableParts} getLabel={spareLabel} onPick={pickSpare} emptyText="No se encontró un repuesto." helper={associatedParts.length ? `${associatedParts.length} asociados al área seleccionada.` : form.id_area ? "Catálogo completo disponible: no hay asociación previa para esta área." : "Selecciona un área para priorizar sus repuestos."} /><label>Cantidad<input required type="number" min="1" value={form.cantidad_solicitada} onChange={(event) => setForm({ ...form, cantidad_solicitada: event.target.value })} /></label><label>Prioridad<select value={form.prioridad} onChange={(event) => setForm({ ...form, prioridad: event.target.value })}><option>Baja</option><option>Media</option><option>Alta</option><option>Crítica</option></select></label><label>Solicitado por<input required value={form.solicitado_por} onChange={(event) => setForm({ ...form, solicitado_por: event.target.value })} /></label></div><label>Motivo / trabajo requerido<input value={form.motivo} onChange={(event) => setForm({ ...form, motivo: event.target.value })} placeholder="Ej.: reposición por mantenimiento preventivo" /></label>{error && <p className="form-error">{error}</p>}<button className="button button-primary">Enviar a aprobación</button></form></div>}</DashboardLayout>;
}
export default Solicitudes;
