import { useEffect, useState } from "react";
import DashboardLayout from "../layouts/DashboardLayout";
import PageHeader from "../components/PageHeader";
import "../styles/usuarios.css";

const API = import.meta.env.VITE_API_URL || "http://localhost:3000/api";
const roles = ["Operario", "Técnico", "Ingeniero", "Administrador"];
const emptyForm = { nombre: "", usuario: "", correo: "", password: "", rol: "Operario" };
const authHeaders = (json = false) => ({ ...(json ? { "Content-Type": "application/json" } : {}), Authorization: `Bearer ${localStorage.getItem("authToken") || ""}` });

function Usuarios() {
  const [users, setUsers] = useState([]); const [loading, setLoading] = useState(true); const [open, setOpen] = useState(false); const [form, setForm] = useState(emptyForm); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = async () => { setLoading(true); try { const response = await fetch(`${API}/usuarios`, { headers: authHeaders() }); setUsers(response.ok ? await response.json() : []); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const create = async (event) => { event.preventDefault(); setSaving(true); setError(""); try { const response = await fetch(`${API}/usuarios`, { method: "POST", headers: authHeaders(true), body: JSON.stringify(form) }); const body = await response.json(); if (!response.ok) throw new Error(body.error); await load(); setOpen(false); setForm(emptyForm); } catch (err) { setError(err.message || "No fue posible crear el usuario."); } finally { setSaving(false); } };
  const save = async (user) => { const response = await fetch(`${API}/usuarios/${user.id}`, { method: "PATCH", headers: authHeaders(true), body: JSON.stringify(user) }); if (response.ok) load(); };
  return <DashboardLayout><PageHeader eyebrow="ADMINISTRACIÓN" title="Usuarios y permisos" description="Crea cuentas y define qué módulos puede utilizar cada persona." action={<button className="button button-primary" onClick={() => { setError(""); setForm(emptyForm); setOpen(true); }}>+ Nuevo usuario</button>} />
    <section className="users-summary"><div><strong>{users.length}</strong><span>usuarios registrados</span></div><p><b>Operario:</b> reporta planta. <b>Técnico:</b> atiende órdenes y solicita repuestos. <b>Ingeniero:</b> planifica e importa. <b>Administrador:</b> gestiona todo.</p></section>
    <section className="users-panel"><header><div><p className="eyebrow">CONTROL DE ACCESOS</p><h2>Usuarios activos y permisos</h2></div></header>{loading ? <p className="empty-state">Cargando usuarios...</p> : <div className="users-table-wrap"><table className="users-table"><thead><tr><th>Usuario</th><th>Nombre</th><th>Correo</th><th>Rol</th><th>Nueva contraseña</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><b>{user.usuario}</b></td><td><input value={user.nombre || ""} onChange={(event) => setUsers(users.map((item) => item.id === user.id ? { ...item, nombre: event.target.value } : item))} /></td><td><input value={user.correo || ""} onChange={(event) => setUsers(users.map((item) => item.id === user.id ? { ...item, correo: event.target.value } : item))} /></td><td><select value={user.rol === "Tecnico" ? "Técnico" : user.rol} onChange={(event) => setUsers(users.map((item) => item.id === user.id ? { ...item, rol: event.target.value } : item))}>{roles.map((role) => <option key={role}>{role}</option>)}</select></td><td><input type="password" minLength="6" placeholder="Sin cambios" value={user.password || ""} onChange={(event) => setUsers(users.map((item) => item.id === user.id ? { ...item, password: event.target.value } : item))} /></td><td><button className={user.estado ? "user-status active" : "user-status"} onClick={() => setUsers(users.map((item) => item.id === user.id ? { ...item, estado: !item.estado } : item))}>{user.estado ? "Activo" : "Inactivo"}</button></td><td><button className="button button-secondary user-save" onClick={() => save(user)}>Guardar</button></td></tr>)}</tbody></table></div>}</section>
    {open && <div className="modal-backdrop"><form className="modal user-modal" onSubmit={create}><div className="modal-header"><div><p className="eyebrow">NUEVA CUENTA</p><h2>Crear usuario</h2><p>La persona verá los módulos definidos por su rol.</p></div><button type="button" onClick={() => setOpen(false)}>×</button></div><div className="form-grid"><label>Nombre completo<input required value={form.nombre} onChange={(event) => setForm({ ...form, nombre: event.target.value })} /></label><label>Usuario<input required pattern="[A-Za-z0-9._-]+" placeholder="Ej.: jlopez" value={form.usuario} onChange={(event) => setForm({ ...form, usuario: event.target.value })} /></label><label>Correo<input type="email" value={form.correo} onChange={(event) => setForm({ ...form, correo: event.target.value })} /></label><label>Rol<select value={form.rol} onChange={(event) => setForm({ ...form, rol: event.target.value })}>{roles.map((role) => <option key={role}>{role}</option>)}</select></label></div><label>Contraseña temporal<input required minLength="6" type="password" value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></label>{error && <p className="form-error">{error}</p>}<div className="manual-machine-actions"><button type="button" className="button button-secondary" onClick={() => setOpen(false)}>Cancelar</button><button className="button button-primary" disabled={saving}>{saving ? "Guardando..." : "Crear usuario"}</button></div></form></div>}
  </DashboardLayout>;
}
export default Usuarios;
